steps:
# Install dependencies
- name: 'python:3.11'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']

# Deploy the Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy cv_optimizer \
        --gen2 \
        --runtime=python311 \
        --region=europe-west2 \
        --source=. \
        --entry-point=cv_optimizer \
        --trigger-http \
        --memory=512MB \
        --timeout=540s \
        --min-instances=0 \
        --max-instances=10 \
        --set-env-vars=ENVIRONMENT=production,LOG_LEVEL=INFO,USE_SECRETS_MANAGER=true

# Set IAM policy for the function to restrict access
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Restrict access to specific service accounts
      gcloud functions add-iam-policy-binding cv_optimizer \
        --gen2 \
        --region=europe-west2 \
        --member=serviceAccount:cv-optimizer-sa@hireable-places.iam.gserviceaccount.com \
        --role=roles/cloudfunctions.invoker

# Optional timeout for the entire build
timeout: '1800s'  # 30 minutes 